sharenotes:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # wx模块的WxStorageController的fetch方法对应的地址
      address: https://wechat.kiwi1.cn/wx/storage/fetch/
#      address: http://localhost:8082/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: litemall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: litemall
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall

  notify:
    mail:
      enable: true
      host: smtp.qq.com
      username: 805344479@qq.com
      password: scyvkutzgxnxbbeh
      sendfrom: 805344479@qq.com
      sendto: 805344479@qq.com
    wx:
      enable: false
      template:
        - name: issue
          templateId: 7vp_guTAdm0orjNAGdn9kKPuG5BxXER23xhwkYKgVS8
        - name: resource
          templateId: pO2oVYNNBKL5XR4_cumeh1I1tP5339Ev1F7UC86rN9g
